<a href="https://colab.research.google.com/github/Aniket-Kumar-7/Machine-Learning/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [261]:
import numpy as np
import pandas as pd
import seaborn as sbn
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [262]:
df=sbn.load_dataset('titanic')

In [263]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [264]:
df.shape

(891, 15)

In [265]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [266]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [267]:
missing_per=(df.isnull().sum()/len(df))*100
cols=missing_per[missing_per>40]
print(cols)

deck    77.216611
dtype: float64

In [268]:
df.drop(['deck'],axis=1,inplace=True)

In [269]:
df.head().shape

(5, 14)

In [270]:
df.isnull().sum()/len(df)

survived       0.000000
pclass         0.000000
sex            0.000000
age            0.198653
sibsp          0.000000
parch          0.000000
fare           0.000000
embarked       0.002245
class          0.000000
who            0.000000
adult_male     0.000000
embark_town    0.002245
alive          0.000000
alone          0.000000
dtype: float64

In [271]:
df['age'].fillna(df['age'].median(),inplace=True)

In [272]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [273]:
df.drop(['alive','who'],axis=1,inplace=True)

In [274]:
df['embarked'].fillna(df['embarked'].mode()[0],inplace=True)
df['embark_town'].fillna(df['embark_town'].mode()[0],inplace=True)

In [275]:
df.isnull().sum()
df.loc[df['age']>=18,'adult_male']=True
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,True,Southampton,False
1,1,1,female,38.0,1,0,71.2833,C,First,True,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,S,Third,True,Southampton,True
3,1,1,female,35.0,1,0,53.1000,S,First,True,Southampton,False
4,0,3,male,35.0,0,0,8.0500,S,Third,True,Southampton,True

In [276]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,True,Southampton,False
1,1,1,female,38.0,1,0,71.2833,C,First,True,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,S,Third,True,Southampton,True
3,1,1,female,35.0,1,0,53.1000,S,First,True,Southampton,False
4,0,3,male,35.0,0,0,8.0500,S,Third,True,Southampton,True

In [277]:
df['embarked'].value_counts()[0]/len(df)*100

np.float64(72.50280583613917)

In [278]:
df.drop(['adult_male'],axis=1,inplace=True)

In [279]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,Southampton,False
1,1,1,female,38.0,1,0,71.2833,C,First,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,S,Third,Southampton,True
3,1,1,female,35.0,1,0,53.1000,S,First,Southampton,False
4,0,3,male,35.0,0,0,8.0500,S,Third,Southampton,True

In [280]:
df.drop(['parch'],axis=1,inplace=True)

In [281]:
df.head()

,survived,pclass,sex,age,sibsp,fare,embarked,class,embark_town,alone
0,0,3,male,22.0,1,7.2500,S,Third,Southampton,False
1,1,1,female,38.0,1,71.2833,C,First,Cherbourg,False
2,1,3,female,26.0,0,7.9250,S,Third,Southampton,True
3,1,1,female,35.0,1,53.1000,S,First,Southampton,False
4,0,3,male,35.0,0,8.0500,S,Third,Southampton,True

In [282]:
df.drop(['embarked'],axis=1,inplace=True)

In [283]:
df.head()

   survived  pclass     sex   age  sibsp     fare  class  embark_town  alone
0         0       3    male  22.0      1   7.2500  Third  Southampton  False
1         1       1  female  38.0      1  71.2833  First    Cherbourg  False
2         1       3  female  26.0      0   7.9250  Third  Southampton   True
3         1       1  female  35.0      1  53.1000  First  Southampton  False
4         0       3    male  35.0      0   8.0500  Third  Southampton   True

In [284]:
df['sex']=df['sex'].map({'male':1,'female':0})

In [285]:
df.head()

   survived  pclass  sex   age  sibsp     fare  class  embark_town  alone
0         0       3    1  22.0      1   7.2500  Third  Southampton  False
1         1       1    0  38.0      1  71.2833  First    Cherbourg  False
2         1       3    0  26.0      0   7.9250  Third  Southampton   True
3         1       1    0  35.0      1  53.1000  First  Southampton  False
4         0       3    1  35.0      0   8.0500  Third  Southampton   True

In [286]:
df['class'].value_counts()
df['class']=df['class'].map({'Third':3,'First':1,'Second':2})

In [287]:
df.head()
df['alone']=df['alone'].map({False:0,True:1})
df.head()

   survived  pclass  sex   age  sibsp     fare class  embark_town  alone
0         0       3    1  22.0      1   7.2500     3  Southampton      0
1         1       1    0  38.0      1  71.2833     1    Cherbourg      0
2         1       3    0  26.0      0   7.9250     3  Southampton      1
3         1       1    0  35.0      1  53.1000     1  Southampton      0
4         0       3    1  35.0      0   8.0500     3  Southampton      1

In [288]:
df['age']=df['age'].astype(int)
df['fare']=df['fare'].round().astype(int)

In [289]:
df.head()
df['embark_town'].value_counts()

embark_town
Southampton    646
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [290]:
df['embark_town'].unique()
df['embark_town']=df['embark_town'].map({'Southampton':1,'Cherbourg':2,'Queenstown':3})

In [291]:
df.head()
df=df.astype(int)

In [292]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

In [293]:
df['embark_town']=label.fit_transform(df['embark_town'])
df['sex']=label.fit_transform(df['sex'])

In [294]:
df['embark_town'].value_counts()
df.head()

   survived  pclass  sex  age  sibsp  fare  class  embark_town  alone
0         0       3    1   22      1     7      3            0      0
1         1       1    0   38      1    71      1            1      0
2         1       3    0   26      0     8      3            0      1
3         1       1    0   35      1    53      1            0      0
4         0       3    1   35      0     8      3            0      1

In [295]:
X=df.drop('survived',axis=1)
y=df['survived']

In [296]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=42)

In [297]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [303]:
y_predict=model.predict(X_test).round().astype(int)
y_predict

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1])

In [299]:
y_test

709    1
439    0
840    0
720    1
39     1
      ..
433    0
773    0
25     1
84     1
10     1
Name: survived, Length: 179, dtype: int64