<a href="https://colab.research.google.com/github/Aniket-Kumar-7/Machine-Learning/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [210]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sbn
import warnings

In [211]:
warnings.filterwarnings('ignore')

In [212]:
df=pd.read_csv(r'/content/train.txt',sep=";",names=['text','emotion'],header=0)

In [213]:
df.head()

                                                text  emotion
0  i can go from feeling so hopeless to so damned...  sadness
1   im grabbing a minute to post i feel greedy wrong    anger
2  i am ever feeling nostalgic about the fireplac...     love
3                               i am feeling grouchy    anger
4  ive been feeling a little burdened lately wasn...  sadness

In [214]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [215]:
emotion_list=df['emotion'].unique()
print(type(emotion_list))

<class 'numpy.ndarray'>

In [216]:
df['text']=df['text'].apply(lambda x:x.lower())
df['emotion']=df['emotion'].apply(lambda x:x.lower())

In [217]:
import string

In [218]:
def remove_punc(text):
  return text.translate(str.maketrans('','',string.punctuation))

In [219]:
df['text']=df['text'].apply(remove_punc)
df['emotion']=df['emotion'].apply(remove_punc)

In [220]:
emotion_number={}
i=0
for emotion in emotion_list:
  emotion_number[emotion]=i
  i=i+1

df['emotion']=df['emotion'].map(emotion_number)

In [221]:
emotion_number

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [222]:
def remove_num(txt):
  new_txt=""
  for i in txt:
    if not i.isdigit():
      new_txt=new_txt+i
  return new_txt

In [223]:
df['text']=df['text'].apply(remove_num)

In [224]:
import re

In [225]:
def advanced_prepr(text):
  text=text.lower()
  text=re.sub(r'https?://\S+|www\.\S+','',text);
  text=re.sub(r'<.*?>','',text)
  text=re.sub(r'@\w+|#\w+','',text)
  text=re.sub(r'\d+','',text)
  text=text.translate(str.maketrans('','',string.punctuation))
  text=re.sub(r'\s+',' ',text).strip()
  return text

In [226]:
df['text']=df['text'].apply(advanced_prepr)

In [227]:
df.head()

                                                text  emotion
0  i can go from feeling so hopeless to so damned...        0
1   im grabbing a minute to post i feel greedy wrong        1
2  i am ever feeling nostalgic about the fireplac...        2
3                               i am feeling grouchy        1
4  ive been feeling a little burdened lately wasn...        0

In [228]:

def remove_emojis(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"  # symbols 🌍
        "\U0001F680-\U0001F6FF"  # transport 🚗
        "\U0001F700-\U0001F77F"  # alchemical
        "\U0001F780-\U0001F7FF"
        "\U0001F800-\U0001F8FF"
        "\U0001F900-\U0001F9FF"  # supplemental 🤖
        "\U0001FA00-\U0001FA6F"
        "\U0001FA70-\U0001FAFF"
        "\U00002700-\U000027BF"  # dingbats ✂️
        "\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub(r'', text)

In [229]:
df['text']=df['text'].apply(remove_emojis)

In [230]:
from nltk.corpus import stopwords

In [231]:
from nltk.tokenize import word_tokenize
import nltk

In [232]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [233]:
stop_words=set(stopwords.words('english'))

In [234]:
df.head()

                                                text  emotion
0  i can go from feeling so hopeless to so damned...        0
1   im grabbing a minute to post i feel greedy wrong        1
2  i am ever feeling nostalgic about the fireplac...        2
3                               i am feeling grouchy        1
4  ive been feeling a little burdened lately wasn...        0

In [235]:
contractions = {
    "im": "i am",
    "i m": "i am",
    "dont": "do not",
    "don t": "do not",
    "cant": "cannot",
    "can t": "cannot",
    "idk": "i do not know",
    "u": "you",
    "r": "are",
    'ive':"i have",
    'I':'i',
    'wasnt':'was not',
    'werent':'were not'
}

In [236]:
def remove_slang(text):
  for key, value in contractions.items():
    text = re.sub(rf'\b{key}\b', value, text)
  return text

In [237]:
df['text']=df['text'].apply(remove_slang)

In [238]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [239]:
def remove_stopwords(text):
  words=text.split()
  cleaned=[]
  for i in words:
    if not i in stop_words:
      cleaned.append(i)
  return ' '.join(cleaned)

In [240]:
print(remove_stopwords(df.loc[1]['text']))

grabbing minute post feel greedy wrong

In [241]:
df['text']=df['text'].apply(remove_stopwords)

In [242]:
print(df)

                                                    text  emotion
0      go feeling hopeless damned hopeful around some...        0
1                 grabbing minute post feel greedy wrong        1
2      ever feeling nostalgic fireplace know still pr...        2
3                                        feeling grouchy        1
4                    feeling little burdened lately sure        0
...                                                  ...      ...
15994      brief time beanbag said anna feel like beaten        0
15995  turning feel pathetic still waiting tables sub...        0
15996                           feel strong good overall        5
15997                        feel like rude comment glad        1
15998                       know lot feel stupid portray        0

[15999 rows x 2 columns]

In [243]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.model_selection import train_test_split

In [244]:
X=df['text']
y=df['emotion']

In [245]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.20,random_state=42)

In [246]:
y_train

676      0
14179    0
7077     4
13004    0
10264    5
        ..
13418    3
5390     5
860      4
15795    5
7270     5
Name: emotion, Length: 12799, dtype: int64

In [247]:
bow_vectorizer=CountVectorizer()

In [248]:
X_train_bow=bow_vectorizer.fit_transform(X_train)
X_test_bow=bow_vectorizer.transform(X_test)

In [249]:
X_test_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 26127 stored elements and shape (3200, 13388)>

In [250]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

multi_nb_model=MultinomialNB()

multi_nb_model.fit(X_train_bow,y_train)

nb_pred=multi_nb_model.predict(X_test_bow)

In [251]:
print(accuracy_score(nb_pred,y_test))

0.766875

In [252]:
from sklearn.linear_model import LogisticRegression

In [253]:
lg_model=LogisticRegression(solver='lbfgs',max_iter=1000)

In [254]:
lg_model.fit(X_train_bow,y_train)

LogisticRegression(max_iter=1000)

In [255]:
lg_pred=lg_model.predict(X_test_bow)

In [256]:
print(accuracy_score(lg_pred,y_test))

0.880625

In [257]:
tfidf=TfidfVectorizer()

In [258]:
print(type(X_train))

<class 'pandas.core.series.Series'>

In [263]:
X_train_tfidf=tfidf.fit_transform(X_train)
X_test_tfidf=tfidf.transform(X_test)

In [264]:
lg_model.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [265]:
multi_nb_model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [261]:
y_tfidf_lg=lg_model.predict(X_test_tfidf)

In [270]:
print(accuracy_score(y_test,y_tfidf_lg))

0.8275

In [268]:
y_tfidf_nb=multi_nb_model.predict(X_test_tfidf)

In [269]:
print(accuracy_score(y_tfidf_nb,y_test))

0.6715625